name: Update Time

on:
  schedule:
    - cron: '*/1 * * * *' # Update every minute

jobs:
  update-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update time.json
        run: |
          echo "{\"currentTime\": \"$(TZ=America/Los_Angeles date +'%Y-%m-%d %H:%M:%S')\"}" > time.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add time.json
          git commit -m "Update time"
          git push
